### ISSUE TITLE
'특행기관' 칼럼에 대한 질문

### ISSUE THREAD

**Issue by ssuummm** [aivocado/cgaside#38]
### '특행기관' 칼럼에 대한 질문
![image (2)](https://github.com/aivocado/cgbside/assets/139437305/b4d1ea44-9e1d-4b2b-b463-03cc4700db1b)

질문1) '특행기관'에 '시-도 본부장'이 기입되어 있는 행은 어떻게 처리하는 것이 좋을까요?
질문2) '특행기관'이 1이지만, '수임기관'이 결측치인 행이 270개가 있습니다. 이러한 행은 어떻게 처리하는 것이 좋을까요?

**Comment by statkclee** [comment]
검토결과...

특행기관이 별도의 셀로 만들어진 데이터는 무시하고(따라서 수임기관 여부도 함께 무시하면 됩니다)

사무유형(소분류)에서 특행기관이라고 체크된 3,852개만 특행사무로 분류해어 처리해주세요
